// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvES9Zu4TCmRtPHVASnJSRZzPKzfLBHPs',
    appId: '1:165714469853:web:48cc5f5a67cec857f64c34',
    messagingSenderId: '165714469853',
    projectId: 'hamus-flutter-app',
    authDomain: 'hamus-flutter-app.firebaseapp.com',
    storageBucket: 'hamus-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaOImHtsuhdZEfpARuIgUEXefDEnTQq2U',
    appId: '1:165714469853:android:10ec5d0f76aa613bf64c34',
    messagingSenderId: '165714469853',
    projectId: 'hamus-flutter-app',
    storageBucket: 'hamus-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAlQfH1hsb5IWFboW3Z3i5rgtF4wObK1s',
    appId: '1:165714469853:ios:cdb3ff35fafd910cf64c34',
    messagingSenderId: '165714469853',
    projectId: 'hamus-flutter-app',
    storageBucket: 'hamus-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.myFbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAlQfH1hsb5IWFboW3Z3i5rgtF4wObK1s',
    appId: '1:165714469853:ios:cdb3ff35fafd910cf64c34',
    messagingSenderId: '165714469853',
    projectId: 'hamus-flutter-app',
    storageBucket: 'hamus-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.myFbApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvES9Zu4TCmRtPHVASnJSRZzPKzfLBHPs',
    appId: '1:165714469853:web:8cbd2cf9f9436b53f64c34',
    messagingSenderId: '165714469853',
    projectId: 'hamus-flutter-app',
    authDomain: 'hamus-flutter-app.firebaseapp.com',
    storageBucket: 'hamus-flutter-app.firebasestorage.app',
  );
}
